### ISSUE TITLE
Bootsy 2.1.0 seems to have broken JavaScript editor menu localization

### ISSUE THREAD

**Issue by driehuis** [volmer/bootsy#125]
With Bootsy 2.0.13, the app in the locale_nl branch of https://github.com/driehuis/bootsy-sample shows a Dutch localized editor menubar. After updating to 2.1.0, the menubar is in English.

I tried loading the bootstrap-wysihtml5.nl before loading bootsy in app/assets/javascripts/application.js but didn't have much luck with that either, and I'm totally out of my depth trying to debug this issue in JavaScript.

**Comment by volmer** [comment]
It looks like you haven't translated [Bootsy's javascript messages](https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/translations.js). I addition to `bootstrap-wysiwyg.nl.js` you also need to have a `bootsy.nl.js` or similar. You can follow [this example](https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/locales/bootsy.pt-BR.js).

I've also updated the README to better reflect this requirement.

**Comment by driehuis** [comment]
That does indeed fix it!

Would you accept a patch the provides a rake task to generate bootsy.#{locale}.js and bootstrap-wysiwyg.#{locale}.js from config/locales, for all locales given in a new setting in config/initializers/bootsy.rb, like, "config.generate_locales = [ 'en', 'pt-BR' ]"?

Having to edit three seperate files with documentation spread out across two websites strikes me as suboptimal (especially because the link to wysihtml5's JavaScript customisation confused me, because that project's github page does not seem to contain the version of wysihtml5 used in Bootsy).

**Comment by volmer** [comment]
The idea of having those in one place (`config/locales`) is good, I don't think a new rake task would make things simpler. Maybe the locale files could be generated in the assets compilation?

**Comment by driehuis** [comment]
Fair enough, I'd have to read up on extending the asset pipeline, but that sound like the better plan.

**Comment by mib32** [comment]
@volmer could you please tell more about js localizing? 
You have an example file - `bootsy/app/assets/javascripts/bootsy/locales/pt-BR.js`, but it is not required anywhere. If i load my translations after `//=require bootsy` it is too late. How do you personally require `pt-BR` translation?

**Comment by volmer** [comment]
@mib32 first of all, try using `master` as I've changed some js localizing keys recently. Then you can have a file like this one: https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/locales/pt-BR.js

The order you require it shouldn't really matter as everything is loaded on `document.ready`.

**Comment by mib32** [comment]
@volmer thanks, the trick was indeed to use the master branch because it unifies bootsy and wysihtml's keys.

*a little note for non Hispanic guys trying to translate wysihtml* 
```
$.fn.wysihtml5.locale.en = $.fn.wysihtml5.locale['en-US'] = {
    font_styles: {
      normal: 'Normal text',
      h1: 'Heading 1',
      h2: 'Heading 2',
      h3: 'Heading 3',
      h4: 'Heading 4',
      h5: 'Heading 5',
      h6: 'Heading 6'
    },
    emphasis: {
      bold: 'Bold',
      italic: 'Italic',
      underline: 'Underline',
      small: 'Small'
    },
    lists: {
      unordered: 'Unordered list',
      ordered: 'Ordered list',
      outdent: 'Outdent',
      indent: 'Indent'
    },
    link: {
      insert: 'Insert link',
      cancel: 'Cancel',
      target: 'Open link in new window'
    },
    image: {
      insert: 'Insert image',
      cancel: 'Cancel'
    },
    html: {
      edit: 'Edit HTML'
    },
    colours: {
      black: 'Black',
      silver: 'Silver',
      gray: 'Grey',
      maroon: 'Maroon',
      red: 'Red',
      purple: 'Purple',
      green: 'Green',
      olive: 'Olive',
      navy: 'Navy',
      blue: 'Blue',
      orange: 'Orange'
    }
  };
```

**Comment by volmer** [comment]
Are you trying to translate it to English? You shouldn't have to, Bootsy always falls back to `en`.

**Comment by mib32** [comment]
@volmer Nope! I pasted it just because I prefer to translate it to my native language from English :smile: Sorry for any misleading

**Comment by volmer** [comment]
I see... That's a very good point, though. I should extract the `en` copies to its own file and reference it on the `README` instead. Thanks for highlighting this!

**Comment by mib32** [comment]
@volmer Cool! While we're at it, i would suggest to add to `README` the way Bootsy gets the locale - through `data-bootsy-locale` attribute on input element or through html's `lang`attribute. Though i guess it's already a work in progress, since you added this so recently! Thanks!

**Comment by volmer** [comment]
Done. Thanks for suggesting!

**Comment by spuyet** [comment]
@volmer I have some trouble with locales, the rubygems version is still not equal to master ?

**Comment by volmer** [comment]
@spuyet I didn't release a new version yet. Please use `master` for now.
